Dev
webion-hub/Webion.Pdf pull request #1
Opened 2023-03-29 13:39 UTC by davidemesso

2023-03-30 08:22 UTC, cala-br requested changes

2023-03-30 08:22 UTC, cala-br commented on Webion.Pdf.Function/FunctionStartup.cs
> +            options.AllowSynchronousIO = true;
Si può togliere?

2023-03-30 08:22 UTC, cala-br commented on Webion.Pdf.Function/Function.cs
> +        return;
```suggestion
        using var pdfStream = new MemoryStream(pdfDest.ToArray());
        pdfStream.Position = 0;
        using var reader = new StreamReader(pdfStream);
        
        var base64 = System.Convert.ToBase64String(pdfDest.GetBuffer());
        
        context.Response.StatusCode = StatusCodes.Status200OK;
        await context.Response.BodyWriter.WriteAsync(Encoding.UTF8.GetBytes(base64));
```

`pdfStream.Position = 0;` si può togliere?

Forse puoi evitare di usare`await context.Response.BodyWriter.WriteAsync()`? Così da accorciare un po' la chiamata

Tipo `await context.Response.WriteAsync(base64, context.GetCancellationToken());`. Nella descrizione del metodo c'è scritto che codifica già in UTF8, per cui non dovrebbe servire neanche farlo a mano

2023-03-30 08:22 UTC, cala-br commented on Webion.Pdf.Function/Function.cs
> +        using var sw = new PdfWriter(pdfDest);
```suggestion
        using var writer = new PdfWriter(pdfDest);

```

2023-03-30 08:22 UTC, cala-br commented on Webion.Pdf.Function/Function.cs
> +        HtmlConverter.ConvertToPdf(html, sw, converterProperties);
```suggestion
        HtmlConverter.ConvertToPdf(html, writer);

```

2023-04-03 08:14 UTC, davidemesso commented on Webion.Pdf.Function/FunctionStartup.cs
> +            options.AllowSynchronousIO = true;
si

2023-04-04 14:12 UTC, cala-br commented on Webion.Pdf.Function/in/input.css
Toglierei se non serve (ho visto che c'è già nel progetto di test)
Idem per `input.html`

2023-04-19 09:50 UTC, cala-br requested changes

2023-04-19 09:50 UTC, cala-br commented on Webion.Pdf.Function/Function.cs
> +}
Mettile in due file separati e con le graffe a capo

2023-04-19 09:50 UTC, cala-br commented on Webion.Pdf.Function/Function.cs
> +        return;
```suggestion
```

2023-04-21 09:57 UTC, cala-br approved these changes

2023-04-21 09:57 UTC, merged